# Generated by Django 3.1.7 on 2021-06-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('age', models.IntegerField(default=23)),
                ('date_emp', models.DateTimeField()),
            ],
        ),
    ]
